DROP TABLE IF EXISTS blattodea;
DROP TABLE IF EXISTS animorph;

CREATE TABLE blattodea (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  habitat TEXT NOT NULL,
  length FLOAT NOT NULL
);

CREATE TABLE animorph (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  morph TEXT NOT NULL,
  minutes FLOAT NOT NULL,
  is_morphed BOOLEAN DEFAULT FALSE
);